# ----------------------------------------
# Site settings
# ----------------------------------------
title: "Scentience WebSocket API"
description: "A lightweight WebSocket API for olfactory communication between Scentience devices, apps, and robots."
# url: "https://scentience.github.io"
# baseurl: "/docs-api"   # change/remove if deploying at root

theme: jekyll-theme-midnight
show_downloads: true
github:
  is_project_page: true
  repository_url: "https://scentience.github.io/docs-api"


# remote_theme: pages-themes/midnight@v0.2.0

# plugins:
#   - jekyll-remote-theme
#   - jekyll-feed
#   - jekyll-seo-tag

# markdown: kramdown
# highlighter: rouge

# include:
#   - README.md

# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: default
#       permalink: /

# collections:
#   docs:
#     output: true