# ----------------------------------------
# Site settings
# ----------------------------------------
title: "Scentience WebSocket API"
description: "A lightweight WebSocket API for olfactory communication between Scentience devices, apps, and robots."
domain: "scentience.github.io"
url: "https://scentience.github.io"
baseurl: "/docs-api-sockets/"   # change/remove if deploying at root
# ----------------------------------------
# Theme settings
# ----------------------------------------
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# ----------------------------------------
# Build settings
# ----------------------------------------

# Ensure README.md is built into the site
include:
  - README.md

# Make README.md act as the homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      permalink: /

# Render docs/*.md as HTML pages
collections:
  docs:
    output: true
