# ----------------------------------------
# Site settings
# ----------------------------------------
title: "Scentience WebSocket API"
description: "A lightweight WebSocket API for olfactory communication between Scentience devices, apps, and robots."
domain: "scentience.github.io"
url: "https://scentience.github.io"
baseurl: "/docs-api-sockets/"   # change/remove if deploying at root
theme: jekyll-theme-midnight

# ----------------------------------------
# Build settings
# ----------------------------------------
markdown: kramdown
highlighter: rouge

# Ensure README.md is included in the build
include:
  - README.md

# Defaults: make README.md the homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      permalink: /

# Collections for docs (so /docs/*.md become HTML pages)
collections:
  docs:
    output: true

# Plugins (safe for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ----------------------------------------
# Navigation (sidebar pulls from _data/navigation.yml)
# ----------------------------------------
